---
- hosts: localhost
  tasks:
    - name: update ntpd
      apt: pkg=ntp state=latest
      notify:
        - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted